  function open_close_menu(){
      if(document.querySelector('.menu_list').style.display=="none"){
        document.querySelector('.menu_list').style.display="block";
        document.querySelector('.widget').style.position="fixed";
    document.querySelector('.widget').style.height="100%";
    document.querySelector('.widget').style.width="20%";
  }
  else{
     document.querySelector('.widget').style.position="relative";
    document.querySelector('.menu_list').style.display="none";
     document.querySelector('.widget').style.height="20%";
    document.querySelector('.widget').style.width="100%";
    document.querySelector('.widget').style.zIndex="100";
  }
      document.querySelector(".container").classList.toggle("change");
}
  function open_close_test(){
    open_close_menu();
    if(document.querySelector('.menu_list').style.display=="block"){    
    document.querySelector('#content3').style.width="60%";
    document.querySelector('#content3').style.left="25%"; 
  }
  else{    
    document.querySelector('#content3').style.width="100%";
    document.querySelector('#content3').style.left="0";  
    document.querySelector('#content3').style.zIndex="1";  
  }
  }
  function open_close_table(){
    open_close_menu();
    if(document.querySelector('.menu_list').style.display=="block"){     
    document.querySelector('.main1').style.width="78vw";
    document.querySelector('.main1').style.marginTop="5vh";
  }
  else{    
    document.querySelector('.main1').style.width="100%";
    document.querySelector('.main1').style.marginTop="20vh";   
  }
  }
   function open_close_top(){
  open_close_menu();
  if(document.querySelector('.menu_list').style.display=="block"){  
    document.querySelector('#real_madrid').style.width="75%";
  document.querySelector('#man_utd').style.width="75%";
  document.querySelector('#barca').style.width="75%";
  document.querySelector('#top_clubs').style.width="75%";
   document.querySelector('#top_clubs').style.marginLeft="25%";
  }
  else{
  document.querySelector('#real_madrid').style.width="100%";
  document.querySelector('#man_utd').style.width="100%";
  document.querySelector('#barca').style.width="100%";
  document.querySelector('#top_clubs').style.width="100%";
   document.querySelector('#top_clubs').style.marginLeft="0";
   }
   }
   function open_close_komanda(){
      open_close_menu();
      if(document.querySelector('.menu_list').style.display=="block"){
       document.querySelector('.field').style.width="80vw";  
       }
       else{ 
      document.querySelector('.widget').style.zIndex="1";
      document.querySelector('#content7').style.zIndex="0";
      document.querySelector('.field').style.width="100%";       
     }
   } 
    function open_close_index(x){
      open_close_menu();
      if(document.querySelector('.menu_list').style.display=="block"){
       document.querySelector('#nov').style.width="60%";  
       document.querySelector('#match').style.width="60%";
       document.querySelector('#match').style.width="60%";
       document.querySelector('#content5').style.position="fixed";
      document.querySelector('#content5').style.width="15%";
      document.querySelector('#content5').style.marginTop="0%"; 
      document.querySelector('#content2').style.position="fixed";
      document.querySelector('#content2').style.width="15%";
       }
       else{      
      document.querySelector('#nov').style.width="100%";  
      document.querySelector('#match').style.width="100%"; 
      document.querySelector('#content5').style.position="relative";
      document.querySelector('#content5').style.width="100%";
      document.querySelector('#content5').style.marginTop="5%"; 
       document.querySelector('#content2').style.position="relative";
      document.querySelector('#content2').style.width="100%";    
     }
   } 